services:
  mysql:
    image: mysql:8.0
    container_name: stage-scraper-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stage_scraper
      MYSQL_USER: scraperuser
      MYSQL_PASSWORD: scraperpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
